# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b943c28c82583e39509ef4fa9a15a5206fef6cc3e3e6fc2ba1a7548b037db1687262890f8086cd66baac160331730b8695ae47085e79e9484f0b4c9385112c87

test:
  secret_key_base: 814c0c71eb43f467782bb2313c20804937d38564655c407121194148255816f110f01d9a6b17dfbbc203ff0e5923f0c7b10244f39edb6e7c949b263c2c98a032

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
